// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBShUUeOfY1qYQl2SIpK91J_A87rWO0iBA',
    appId: '1:1013963038740:web:ba270d276df51b9ebbc701',
    messagingSenderId: '1013963038740',
    projectId: 'fireproject1-e9fc9',
    authDomain: 'fireproject1-e9fc9.firebaseapp.com',
    storageBucket: 'fireproject1-e9fc9.firebasestorage.app',
    measurementId: 'G-8E9HTYBFK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvHm_yajWo-qovx9qeYCAi2Gty-zJEf2s',
    appId: '1:1013963038740:android:51d2f977a02eea00bbc701',
    messagingSenderId: '1013963038740',
    projectId: 'fireproject1-e9fc9',
    storageBucket: 'fireproject1-e9fc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMq2Xg3XQGvNnKI1q7pDuojmewTq6EmLU',
    appId: '1:1013963038740:ios:5e54f8a72be7ebb2bbc701',
    messagingSenderId: '1013963038740',
    projectId: 'fireproject1-e9fc9',
    storageBucket: 'fireproject1-e9fc9.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMq2Xg3XQGvNnKI1q7pDuojmewTq6EmLU',
    appId: '1:1013963038740:ios:5e54f8a72be7ebb2bbc701',
    messagingSenderId: '1013963038740',
    projectId: 'fireproject1-e9fc9',
    storageBucket: 'fireproject1-e9fc9.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBShUUeOfY1qYQl2SIpK91J_A87rWO0iBA',
    appId: '1:1013963038740:web:afce6a80ca46a988bbc701',
    messagingSenderId: '1013963038740',
    projectId: 'fireproject1-e9fc9',
    authDomain: 'fireproject1-e9fc9.firebaseapp.com',
    storageBucket: 'fireproject1-e9fc9.firebasestorage.app',
    measurementId: 'G-4W0ZNYK61J',
  );
}
